config/routes.rb
RailsPress::Application.routes.draw do

  #  Admin
  #-----------------------------------------------
  namespace :admin do
    root to: 'admin#index'

    devise_scope :user do
      get :login, to: 'admin#login'
      get :logout, to: 'admin#logout'
    end

    resources :pages
    resources :posts do
      collection do
        get :comments, to: 'comments#inbox'
        get :tags
      end

      resources :comments do
        member do
          post :like
          post :dislike
          post :unlike
        end
      end
    end
    resources :users
    resources :media

    resources :notifications, except: %w[show edit]

    resources :activities, only: :index do
      collection do
        get :dashboard
      end
    end

    resources :settings
  end

  #  Device for Commenter
  #-----------------------------------------------
  devise_for :users,
    path: '',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }

  #  OmniAuth
  #-----------------------------------------------
  get '/auth/:provider/callback' => 'oauths#callback'
  delete '/auth/:provider' => 'oauths#destroy'

  #  Commenter
  #-----------------------------------------------
  get :commenter, to: 'users#edit'
  put :commenter, to: 'users#update'
  delete :commenter, to: 'users#destroy'

  #  Blog
  #-----------------------------------------------
  resources :posts, only: %w[index show] do
    resources :comments
  end

  #  Pages / Static Pages
  #-----------------------------------------------
  root to: 'pages#index'
  get '/:id(/:id2)(/:id3)' => 'pages#show', as: :page

end

app/views/admin/pages/_form.haml
#main
  = form_for [:admin, @page] do |f|

    %table.form
      %tr
        %td
          = f.label :title, 'タイトル'
        %td
          = f.text_field :title, class: 'text'

      %tr
        %td
          = f.label :slug, 'URL'
        %td
          = f.text_field :slug, class: 'text'

      %tr
        %td
          = f.label :content, '本文'
        %td
          = f.text_area :content, class: 'textarea', size: '50x5'

      %tr
        %td
          = f.label :excerpt, '抜粋'
        %td
          = f.text_area :excerpt, class: 'textarea', size: '50x5'

      %tr.doubled
        %td{ colspan: 2 }
          = f.submit nil, class: 'btn btn-primary'

app/views/admin/pages/_form.html.haml
#main
  = form_for [:admin, @page] do |f|

    %table.form
      %tr
        %td
          = f.label :title, 'タイトル'
        %td
          = f.text_field :title, class: 'text'

      %tr
        %td
          = f.label :slug, 'URL'
        %td
          = f.text_field :slug, class: 'text'

      %tr
        %td
          = f.label :content, '本文'
        %td
          = f.text_area :content, class: 'textarea', size: '50x5'

      %tr
        %td
          = f.label :excerpt, '抜粋'
        %td
          = f.text_area :excerpt, class: 'textarea', size: '50x5'

      %tr.doubled
        %td{ colspan: 2 }
          = f.submit nil, class: 'btn btn-primary'

app/views/admin/pages/edit.haml
= render 'form'

app/views/admin/pages/edit.html.haml
= render 'form'

app/views/admin/pages/index.haml
#main
  %ul
    - @pages.each do |page|
      %li
        = link_to page.title, edit_admin_page_path(page)
        %br
        = link_to '[edit]', edit_admin_page_path(page)
        = link_to '[delete]', admin_page_path(page), remote: true, method: :delete

app/views/admin/pages/index.html.haml
#main
  %ul
    - @pages.each do |page|
      %li
        = link_to page.title, edit_admin_page_path(page)
        %br
        = link_to '[edit]', edit_admin_page_path(page)
        = link_to '[delete]', admin_page_path(page), remote: true, method: :delete

app/views/admin/pages/new.haml
= render 'form'

app/views/admin/pages/new.html.haml
= render 'form'